apiVersion: apps/v1
kind: Deployment
metadata:
  name: tribe-ai-app
  labels:
    app: tribe-ai-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tribe-ai-app
  template:
    metadata:
      labels:
        app: tribe-ai-app
    spec:
      containers:
      - name: tribe-ai-app
        image: ghcr.io/lunamae24/tribe-ai-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: APP_ENV
          value: "production"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: tribe-ai-secrets
              key: openai-api-key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tribe-ai-secrets
              key: secret-key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tribe-ai-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tribe-ai-service
spec:
  selector:
    app: tribe-ai-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tribe-ai-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tribe-ai-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
